server:
  port: 8081
spring:
  profiles:
    active: production
  http:
    encoding:
      charset: UTF-8
      enabled: true
  main:
    allow-circular-references: true
  datasource:
    url: postgresql://127.0.0.1:5432/accidents
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver