server:
  port: 8081
file:
  directory: files
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true